# Generated by Django 3.1.14 on 2022-06-20 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0004_auto_20220617_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='descripton',
            field=models.TextField(blank=True),
        ),
    ]
