# Generated by Django 3.1.14 on 2022-07-13 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0015_auto_20220712_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonelementtype',
            name='strong_against',
            field=models.ManyToManyField(blank=True, to='pokemon_entities.PokemonElementType'),
        ),
        migrations.AlterField(
            model_name='pokemonelementtype',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Изображение элемента'),
        ),
        migrations.AlterField(
            model_name='pokemonelementtype',
            name='title',
            field=models.CharField(max_length=50, unique=True, verbose_name='Элемент покемона'),
        ),
    ]
